"""
Merge all exported OBJ files into a single combined OBJ for the flythrough viewer.

Usage:
    python scripts/merge_objs.py [--out <output-path>] [--faced-only] [--min-verts N]

Output: merged.obj in Exports/ by default.
"""
from __future__ import annotations

import argparse
import glob
import os
import sys
from pathlib import Path


def parse_obj(path: str) -> tuple[list[str], list[str], list[str], list[str]]:
    """Parse an OBJ file, returning (vertices, normals, texcoords, faces)."""
    vertices: list[str] = []
    normals: list[str] = []
    texcoords: list[str] = []
    faces: list[str] = []

    with open(path, encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n")
            if line.startswith("v "):
                vertices.append(line)
            elif line.startswith("vn "):
                normals.append(line)
            elif line.startswith("vt "):
                texcoords.append(line)
            elif line.startswith("f "):
                faces.append(line)

    return vertices, normals, texcoords, faces


def offset_face_indices(
    face_line: str,
    v_offset: int,
    vt_offset: int,
    vn_offset: int,
    src_v_count: int,
    src_vt_count: int,
    src_vn_count: int,
) -> str:
    """Rewrite face indices with given offsets.

    Negative OBJ indices are relative to the end of the current file's geometry.
    We resolve them to positive using the source file counts, then apply the global offset.
    """
    parts = face_line.split()
    new_parts = ["f"]
    for group in parts[1:]:
        indices = group.split("/")

        # Vertex index
        vi_str = indices[0]
        if vi_str:
            vi = int(vi_str)
            if vi < 0:
                vi = src_v_count + vi + 1  # e.g. -1 → src_v_count (last vertex)
            vi += v_offset
        else:
            vi = 0

        # Texcoord index
        vti = ""
        if len(indices) > 1 and indices[1]:
            vt = int(indices[1])
            if vt < 0:
                vt = src_vt_count + vt + 1
            vt += vt_offset
            vti = str(vt)

        # Normal index
        vni = ""
        if len(indices) > 2 and indices[2]:
            vn = int(indices[2])
            if vn < 0:
                vn = src_vn_count + vn + 1
            vn += vn_offset
            vni = str(vn)

        if vti or vni:
            new_parts.append(f"{vi}/{vti}/{vni}")
        else:
            new_parts.append(str(vi))

    return " ".join(new_parts)


def merge_objs(
    obj_paths: list[str],
    out_path: str,
    verbose: bool = False,
) -> dict:
    """Merge multiple OBJ files into one."""
    all_vertices: list[str] = []
    all_normals: list[str] = []
    all_texcoords: list[str] = []
    all_faces: list[str] = []

    total_v = 0
    total_vn = 0
    total_vt = 0
    total_f = 0
    merged_count = 0
    skipped = 0

    for i, path in enumerate(obj_paths):
        vertices, normals, texcoords, faces = parse_obj(path)

        if not vertices:
            skipped += 1
            if verbose:
                print(f"  [{i+1}/{len(obj_paths)}] SKIP (no verts): {os.path.basename(path)}")
            continue

        v_offset = total_v
        vn_offset = total_vn
        vt_offset = total_vt
        src_v_count = len(vertices)
        src_vn_count = len(normals)
        src_vt_count = len(texcoords)

        # Add raw geometry
        all_vertices.extend(vertices)
        all_normals.extend(normals)
        all_texcoords.extend(texcoords)

        # Offset and add faces (passing source counts for negative index resolution)
        for face in faces:
            all_faces.append(
                offset_face_indices(face, v_offset, vt_offset, vn_offset, src_v_count, src_vt_count, src_vn_count)
            )

        merged_count += 1
        total_v += len(vertices)
        total_vn += len(normals)
        total_vt += len(texcoords)
        total_f += len(faces)

        if verbose and (i < 5 or i >= len(obj_paths) - 2 or i % 50 == 0):
            rel = os.path.relpath(path, os.path.dirname(out_path)) if os.path.dirname(out_path) else path
            print(f"  [{i+1}/{len(obj_paths)}] {rel}: {len(vertices)}v {len(faces)}f")

    # Write merged OBJ
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Merged RIFT world geometry\n")
        f.write(f"# {merged_count} meshes, {total_v} vertices, {total_f} faces\n")
        f.write("# Generated by scripts/merge_objs.py\n\n")

        for v in all_vertices:
            f.write(v + "\n")
        if all_normals:
            f.write("\n")
            for vn in all_normals:
                f.write(vn + "\n")
        if all_texcoords:
            f.write("\n")
            for vt in all_texcoords:
                f.write(vt + "\n")
        if all_faces:
            f.write("\n")
            for face in all_faces:
                f.write(face + "\n")

    return {
        "merged_count": merged_count,
        "skipped": skipped,
        "total_vertices": total_v,
        "total_normals": total_vn,
        "total_texcoords": total_vt,
        "total_faces": total_f,
        "output_path": out_path,
        "output_size": os.path.getsize(out_path),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Merge RIFT exported OBJs into one file")
    parser.add_argument("--out", default="Exports/merged.obj", help="Output path (default: Exports/merged.obj)")
    parser.add_argument("--faced-only", action="store_true", help="Only include meshes with faces")
    parser.add_argument("--min-verts", type=int, default=0, help="Minimum vertex count per mesh")
    parser.add_argument("--max-meshes", type=int, default=0, help="Max meshes to merge (0 = all)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    args = parser.parse_args()

    # Find all OBJs
    project_root = Path(__file__).resolve().parent.parent
    exports_dir = project_root / "Exports"

    # Merge
    out_path = str(project_root / args.out)
    out_abs = os.path.abspath(out_path)

    obj_paths = sorted(glob.glob(str(exports_dir / "**/*.obj"), recursive=True))
    # Exclude the output file itself from the input set
    obj_paths = [p for p in obj_paths if os.path.abspath(p) != out_abs]
    print(f"Found {len(obj_paths)} OBJ files (excluding output)")

    if not obj_paths:
        print("ERROR: no OBJ files found", file=sys.stderr)
        return 1

    # Filter
    filtered = []
    for p in obj_paths:
        vertices, _, _, faces = parse_obj(p)
        if args.faced_only and not faces:
            continue
        if len(vertices) < args.min_verts:
            continue
        filtered.append(p)

    print(f"After filtering: {len(filtered)} OBJs (faced_only={args.faced_only}, min_verts={args.min_verts})")

    if args.max_meshes > 0 and len(filtered) > args.max_meshes:
        print(f"Limiting to {args.max_meshes} meshes")
        filtered = filtered[: args.max_meshes]

    result = merge_objs(filtered, out_path, verbose=args.verbose)

    print(f"\nMerged: {result['merged_count']} meshes, {result['skipped']} skipped")
    print(f"  Vertices: {result['total_vertices']:,}")
    print(f"  Normals: {result['total_normals']:,}")
    print(f"  TexCoords: {result['total_texcoords']:,}")
    print(f"  Faces: {result['total_faces']:,}")
    print(f"  Output: {result['output_path']} ({result['output_size']:,} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
